version: '3.3'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  # websockets:
  #   image: casino/websockets:latest
  #   build: ./websockets
  #   ports:
  #     - "17005:80"
  backend:
    image: casino/backend:latest
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "17006:80"
    depends_on:
      - db
    restart: always
  frontend:
    image: casino/frontend:latest
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "17007:3000"
    restart: always
  nginx:
    image: casino/nginx:latest
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "15223:80"
    restart: always
  # cron:
  #   image: casino/cron:latest
  #   build: ./cron
  #   depends_on:
  #     - nginx
  #   restart: always


volumes:
  database:
